'use strict';

const path = require('path');
const fs   = require('fs');
const chalk = require('chalk');

const { requireServerRoot, getResourcesDir } = require('../../utils/server-root');
const { scanModules } = require('../../utils/lua-parser');
const { normalizeModuleName } = require('../../generators/index');

function aiContextCommand(program) {
  program
    .command('ai:context')
    .description('Generate AGENTS.md from installed modules')
    .option('-m, --module <module>', 'Generate context for a specific module only')
    .option('-o, --output <path>',   'Output file path', 'AGENTS.md')
    .action((options) => { run(options); });
}

function run(options) {
  const serverRoot   = requireServerRoot();
  const resourcesDir = getResourcesDir(serverRoot);
  let   modules      = scanModules(resourcesDir);

  if (options.module) {
    const name = normalizeModuleName(options.module);
    modules    = modules.filter(m => m.name === name);
    if (modules.length === 0) {
      console.error(chalk.red(`✖ Module not found: ${name}`));
      process.exit(1);
    }
  }

  const lines = [];
  lines.push('# Shiva Server — AI Agent Context');
  lines.push('');
  lines.push('> Auto-generated by `shiva ai:context`. Do not edit manually.');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('## Installed Modules');
  lines.push('');
  lines.push(`${modules.length} module(s) installed.`);
  lines.push('');

  for (const mod of modules) {
    const m = mod.manifest;
    lines.push(`### ${mod.name}`);
    lines.push('');
    if (m.description) lines.push(m.description);
    lines.push('');
    lines.push(`- **Version**: ${m.version || '?'}`);
    if ((m.dependencies || []).length > 0) {
      lines.push(`- **Dependencies**: ${m.dependencies.join(', ')}`);
    }
    if ((m.provides || []).length > 0) {
      lines.push(`- **Provides**: ${m.provides.join(', ')}`);
    }
    if ((m.events || []).length > 0) {
      lines.push('- **Events**:');
      m.events.forEach(e => lines.push(`  - \`${e}\``));
    }
    if ((m.migrations || []).length > 0) {
      lines.push(`- **Migrations**: ${m.migrations.length}`);
    }
    lines.push('');
  }

  const contractsDir = path.join(serverRoot, 'shared', 'contracts');
  if (fs.existsSync(contractsDir)) {
    const contracts = fs.readdirSync(contractsDir).filter(f => f.endsWith('.lua'));
    if (contracts.length > 0) {
      lines.push('## Contracts');
      lines.push('');
      contracts.forEach(f => lines.push(`- \`${f.replace('.lua', '')}\``));
      lines.push('');
    }
  }

  const outPath = path.resolve(serverRoot, options.output);
  fs.writeFileSync(outPath, lines.join('\n'), 'utf-8');

  console.log('');
  console.log(chalk.green(`✔ Generated ${path.relative(process.cwd(), outPath)}`));
  console.log(chalk.gray(`  ${modules.length} modules documented.`));
  console.log('');
}

module.exports = aiContextCommand;
